"""empty message

Revision ID: 5dc761aababf
Revises: 4c5ac7e6b475
Create Date: 2020-11-19 12:34:10.633571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dc761aababf'
down_revision = '4c5ac7e6b475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('org_id', sa.String(), nullable=True))
    op.add_column('work', sa.Column('org_location', sa.String(), nullable=True))
    op.add_column('work', sa.Column('org_name', sa.String(), nullable=True))
    op.add_column('work', sa.Column('person_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'work', ['org_name'])
    op.create_unique_constraint(None, 'work', ['org_id'])
    op.create_unique_constraint(None, 'work', ['org_location'])
    op.create_foreign_key(None, 'work', 'person', ['person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work', type_='foreignkey')
    op.drop_constraint(None, 'work', type_='unique')
    op.drop_constraint(None, 'work', type_='unique')
    op.drop_constraint(None, 'work', type_='unique')
    op.drop_column('work', 'person_id')
    op.drop_column('work', 'org_name')
    op.drop_column('work', 'org_location')
    op.drop_column('work', 'org_id')
    # ### end Alembic commands ###
