"""empty message

Revision ID: 688d2f0c8fd9
Revises: fd3fbe52568c
Create Date: 2020-11-19 17:41:34.433713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688d2f0c8fd9'
down_revision = 'fd3fbe52568c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('work_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'person', 'work', ['work_id'], ['id'])
    op.drop_constraint('work_person_id_fkey', 'work', type_='foreignkey')
    op.drop_column('work', 'person_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('work_person_id_fkey', 'work', 'person', ['person_id'], ['id'])
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.drop_column('person', 'work_id')
    # ### end Alembic commands ###
