"""empty message

Revision ID: 94ab44d6b46b
Revises: 
Create Date: 2020-11-17 20:18:45.691780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ab44d6b46b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hrapp_employees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hrapp_employees',
    sa.Column('emp_no', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('salary', sa.REAL(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('emp_no', name='hrapp_employees_pkey')
    )
    # ### end Alembic commands ###
