"""empty message

Revision ID: fd3fbe52568c
Revises: 5dc761aababf
Create Date: 2020-11-19 12:47:46.435756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3fbe52568c'
down_revision = '5dc761aababf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('work_org_id_key', 'work', type_='unique')
    op.drop_constraint('work_org_location_key', 'work', type_='unique')
    op.drop_constraint('work_org_name_key', 'work', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('work_org_name_key', 'work', ['org_name'])
    op.create_unique_constraint('work_org_location_key', 'work', ['org_location'])
    op.create_unique_constraint('work_org_id_key', 'work', ['org_id'])
    # ### end Alembic commands ###
